---
title: "01-cmap_score"
date: "Compiled at `r format(Sys.time(), '%Y-%m-%d %H:%M:%S', tz = 'UTC')` UTC"
output: github_document
params:
  name: "01-cmap_score" # change if you rename file
---

```{r here, message=FALSE}
here::i_am(paste0(params$name, ".Rmd"), uuid = "680691c5-1c3d-4f78-8e3e-17580c56f279")
```

The purpose of this document is to calculate connectivity score using [RCSM](https://github.com/Jasonlinchina/RCSM).

```{r packages}
library("conflicted")
library(here)
library(readxl)
library(tidyverse)
source("../R/utils.R")
```

```{r directories}
# create or *empty* the target directory, used to write this file's data: 
projthis::proj_create_dir_target(params$name, clean = TRUE)

# function to get path to target directory: path_target("sample.csv")
path_target <- projthis::proj_path_target(params$name)

# function to get path to previous data: path_source("00-import", "sample.csv")
path_source <- projthis::proj_path_source(params$name)
```

## Tasks

The first task is ...

```{r}
load(path_source("00-create_d2m_s2m_profile", "profiles.Rdata"))
```

```{r}
#!/usr/bin/env Rscript
library(argparser)

p <- arg_parser("Calculating connectivity-map score")
p <- add_argument(p, "rdata", help="profiles.Rdata")
p <- add_argument(p, "method", help="KSScore, XSumScore, GSEAweight0Score, GSEAweight1Score, GSEAweight2Score, ZhangScore")
p <- add_argument(p, "permuteNum", help="10000")
p <- add_argument(p, "ncpu", help="10")
p <- add_argument(p, "topN", help="500")
argv <- parse_args(p)


```




```{r cmap_score}
# Calculate cmap score for each disease
cmap_score <- list()
for (disease in disease_names[1:2]) {
  cmap_score[[dname]] <- run_cmap(profile_s2m, 
                                  profile_d2m, 
                                  disease, 
                                  method=method, 
                                  permuteNum = ncpu, 
                                  ncpu = ncpu,
                                  topN = topN)
}

saveRDS(cmap_score, file = output)
``

## Files written

These files have been written to the target directory, ```r paste0("data/", params$name)```:

```{r list-files-target}
projthis::proj_dir_info(path_target())
```
