name: DockerHub build and push

on:
  push:
    tags:
      - 'd*'
      - 'v*'

jobs:
  docker:

    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      # Check out code
      - name: Checkout
        uses: actions/checkout@v3

      # Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # DockerHub Login      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: jinlongru/deepsmirud_web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max